### ISSUE TITLE
Feedback ignoring background

### ISSUE THREAD

**Issue by BTWS2** [BTWS2/judge-turtle#17]
This feature request tries to make the feedback more meaningful. `2209/2500 pixels correct` doesn't say that much, but 88% is already better.

Background pixels are correct by default, so count them separately (see below). E.g. square with a black border and transparant inside. A blank canvas is already 90%+ correct. If the number of black pixels is counted, this results in 0% correct.

* Absolute and percentage difference of total pixels, e.g. `950/1000 (95%) pixels correct` (current situation, but add percentage)
* Absolute and percentage difference of mismatched (non-background) pixels, e.g. `900/1000 (90%) foreground pixels correct`
* User specifies background color in `config.json` (default if not mentioned is transparant). e.g. `"background-color": "white"`

Docs:
- https://github.ugent.be/brewille/turtle/blob/master/non_background.py

Use https://pypi.org/project/colour/ or [the color map in svg_turtle](https://github.com/donkirkby/svg-turtle/blob/b0144c532842253569ac6471a11ad7fa59bfd2b0/svg_turtle/svg_turtle.py#L181) to convert between colour formats.

Edit: This is what I meant. The score isn't 90%+, but a more realistic score, 20% similarity.
![image](https://user-images.githubusercontent.com/56451049/177526461-13e07943-44e9-4c2e-837d-cdff222f1922.png)

**Comment by inteon** [comment]
fixed in 2c7169c9106d480041de5208778dc39782ce8227
