### ISSUE TITLE
Background is ignored and not shown

### ISSUE THREAD

**Issue by BTWS2** [BTWS2/judge-turtle#22]
- [x] https://naos.ugent.be/nl/submissions/983293/
- [x] https://github.ugent.be/brewille/oef_turtle/tree/master/circle

Local output:
![image](https://user-images.githubusercontent.com/56451049/177191202-78bdbb67-0aa7-4c38-a1f4-7296e7f518e6.png)

**Comment by inteon** [comment]
fixed in 07272d1d6b657665bb56e244e3192ada6256caae
