### ISSUE TITLE
Check Shellcheck warnings

### ISSUE THREAD

**Issue by BTWS2** [BTWS2/judge-turtle#26]
- [x] https://github.com/koalaman/shellcheck/wiki/SC2164
- [x] https://github.com/koalaman/shellcheck/wiki/SC2046
- [x] https://github.com/koalaman/shellcheck/wiki/SC2086
- [x] https://github.com/koalaman/shellcheck/wiki/SC2068

See https://github.com/BTWS2/judge-turtle/commit/5bba9de1dd79024c8085ba2d327655b377f5690c

**Comment by inteon** [comment]
fixed in 7f3d329ac4a0043c7f5bff75ea5e659e52f6fbb0
