### ISSUE TITLE
Don't crash if `solution.py` could not be found

### ISSUE THREAD

**Issue by BTWS2** [BTWS2/judge-turtle#31]
Show error instead.

Edit:
- [x] https://naos.ugent.be/nl/submissions/983425/
![image](https://user-images.githubusercontent.com/56451049/177520297-63c80f02-eb63-4a8a-b5bc-6696f4b4452b.png)

**Comment by inteon** [comment]
Could you give an example of such a crash?

**Comment by BTWS2** [comment]
> Could you give an example of such a crash?

Yes, I've updated the description.

**Comment by inteon** [comment]
fixed in 6b46101a5343029fa4f2fa60b66e44d308271eac
